# Generated by Django 4.0.4 on 2022-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date_joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
